# These are supported funding model platforms

github: [chicogong]
# patreon: # Replace with your Patreon username
# ko_fi: # Replace with your Ko-fi username
# open_collective: # Replace with your Open Collective username
# custom: ['https://example.com/sponsor']
